parameters:
    pim_import_export.transformer.product.class:                Pim\Bundle\ImportExportBundle\Transformer\OrmProductTransformer
    pim_import_export.transformer.property.entity.class:        Pim\Bundle\ImportExportBundle\Transformer\Property\EntityTransformer
    pim_import_export.transformer.property.media.class:         Pim\Bundle\ImportExportBundle\Transformer\Property\MediaTransformer
    pim_import_export.transformer.property.date.class:          Pim\Bundle\ImportExportBundle\Transformer\Property\DateTransformer
    pim_import_export.transformer.property.metric.class:        Pim\Bundle\ImportExportBundle\Transformer\Property\MetricTransformer
    pim_import_export.transformer.property.prices.class:        Pim\Bundle\ImportExportBundle\Transformer\Property\PricesTransformer

services:
    pim_import_export.transformer.product:
        class: '%pim_import_export.transformer.product.class%'
        public: false
        arguments:
            - '@pim_catalog.manager.product'
            - '@pim_import_export.product_validator'
            - '@pim_import_export.attribute_cache'
            - '@property_accessor'

    pim_import_export.transformer.property.entity:
        class: '%pim_import_export.transformer.property.entity.class%'
        arguments:
            - '@pim_import_export.entity_cache'
        public: false
        tags:
            - name: pim_import_export.transformer.product.property
              property_path: family
              class: PimCatalogBundle:Family
            - name: pim_import_export.transformer.product.property
              property_path: categories
              class: PimCatalogBundle:Category
              multiple: true
            - name: pim_import_export.transformer.product.property
              property_path: groups
              class: PimCatalogBundle:Group
              multiple: true
            - name: pim_import_export.transformer.product.attribute
              backend_type: option
              class: PimCatalogBundle:AttributeOption
            - name: pim_import_export.transformer.product.attribute
              backend_type: options
              class: PimCatalogBundle:AttributeOption
              multiple: true

    pim_import_export.transformer.attribute.media:
        class: '%pim_import_export.transformer.property.media.class%'
        public: false
        tags:
            - name: pim_import_export.transformer.product.attribute
              backend_type: media

    pim_import_export.transformer.attribute.prices:
        class: '%pim_import_export.transformer.property.prices.class%'
        public: false
        arguments:
            - '@pim_catalog.manager.currency'
        tags:
            - name: pim_import_export.transformer.product.attribute
              backend_type: prices

    pim_import_export.transformer.attribute.metric:
        class: '%pim_import_export.transformer.property.metric.class%'
        public: false
        tags:
            - name: pim_import_export.transformer.product.attribute
              backend_type: metric

    pim_import_export.transformer.attribute.date:
        class: '%pim_import_export.transformer.property.date.class%'
        public: false
        tags:
            - name: pim_import_export.transformer.product.attribute
              backend_type: date
