group_types:
    VARIANT:
        entity: Pim\Bundle\CatalogBundle\Entity\VariantGroup
    X_SELL:
        entity: Pim\Bundle\CatalogBundle\Entity\Group
    ADDITIONAL:
        entity: Pim\Bundle\CatalogBundle\Entity\Group
    RELATED:
        entity: Pim\Bundle\CatalogBundle\Entity\Group
